### ISSUE TITLE
install without running

### ISSUE THREAD

**Issue by itaysk** [goreleaser/get#4]
it would be nice if a variant of this could just install goreleaser, without executing it (this is also what the name "get" implies).
I propose to add another git.io alias: `git.io/getgoreleaser` that just skip the last line in the script.
I'm happy to submit a PR if this makes sense.

**Comment by cpanato** [comment]
+1

**Comment by cpanato** [comment]
wdyt @caarlos0

**Comment by caarlos0** [comment]
this is script is pretty much abandoned... we should probably create a new one at some point

**Comment by caarlos0** [comment]
there's a new script now, but it also only runs

installs can be done using package managers et all, imho not worth spending much time in this
